version: "3.9"

services:
  frontend:
    image: cglass1982/portfolio_frontend
    volumes:
      - react_build:/react/build
      - /react/node_modules
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html/
    depends_on:
      - frontend
volumes:
  react_build: